In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(
    "reddit_preprocessed.csv"
)

df.head()

,Unnamed: 0,clean_comment,category,word_count
0,0,family mormon never tried explain still stare ...,1,26
1,1,buddhism much lot compatible christianity espe...,1,140
2,2,seriously say thing first get complex explain ...,-1,46
3,3,learned want teach different focus goal not wr...,0,15
4,4,benefit may want read living buddha living chr...,1,68

In [3]:
X = df["clean_comment"]

y = df["category"]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [6]:
def run_feature_experiment(max_features):

    tfidf = TfidfVectorizer(
        ngram_range=(1,3),
        max_features=max_features
    )

    X_train_vec = tfidf.fit_transform(
        X_train
    )

    X_test_vec = tfidf.transform(
        X_test
    )

    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=15,
        random_state=42
    )

    model.fit(
        X_train_vec,
        y_train
    )

    y_pred = model.predict(
        X_test_vec
    )

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    return accuracy

In [7]:
feature_sizes = [
    1000,
    2000,
    3000,
    5000,
    7000,
    10000
]

In [8]:
results = []

for feature_size in feature_sizes:

    accuracy = run_feature_experiment(
        feature_size
    )

    results.append(
        [feature_size, accuracy]
    )

    print(
        f"Features: {feature_size} | Accuracy: {accuracy:.4f}"
    )

Features: 1000 | Accuracy: 0.6682
Features: 2000 | Accuracy: 0.6560
Features: 3000 | Accuracy: 0.6582
Features: 5000 | Accuracy: 0.6468
Features: 7000 | Accuracy: 0.6502
Features: 10000 | Accuracy: 0.6474

In [9]:
results_df = pd.DataFrame(
    results,
    columns=[
        "Max Features",
        "Accuracy"
    ]
)

results_df

   Max Features  Accuracy
0          1000  0.668248
1          2000  0.656047
2          3000  0.658216
3          5000  0.646828
4          7000  0.650217
5         10000  0.647370

In [10]:
results_df.sort_values(
    by="Accuracy",
    ascending=False
)

   Max Features  Accuracy
0          1000  0.668248
2          3000  0.658216
1          2000  0.656047
4          7000  0.650217
5         10000  0.647370
3          5000  0.646828